# =========================================================================
# DATABASE CONFIGURATION (BINCOM E-COMMERCE)
# =========================================================================
db.driver=com.mysql.cj.jdbc.Driver

# --- Local Database Configuration ---
db.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
db.username=root
db.password=



# Email Configuration (Gmail SMTP)
# TODO: Replace with your real Gmail + App Password
mail.host=smtp.gmail.com
mail.port=587
mail.username=your_email@gmail.com
mail.password=your_app_password
