services:
  - type: web
    name: bincom-ecommerce
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_FORCE_SEED
        value: "false"
      - key: HIBERNATE_HBM2DDL_AUTO
        value: "none"
